### PR TITLE
StatelessProgrammableSwitch and ServiceLabel

### PR DESCRIPTION
**Pull request by petermm**
- [x] double verified against specification
- [x] added sensors to docs in mix.exs
- [x] added characteristics to docs in mix.exs

### CODE REVIEW

**Comment by mtrudel** [comment]
@petermm have you had a chance to look at this? Just looping outstanding issues and wondering about your feedback on the proposal here.

**Comment by petermm** [comment]
pardon the hiatus - will review and do a "real" world test of it over the weekend!

I assume StatelessProgrammableSwitch is "the pattern" for accessing/doing homekit automation from elixir - eg. you cannot know the state of the kitchen light - but you can fire a StatelessProgrammableSwitch event 10pm that through homekit automation turns kitchen light off etc.

**Comment by hez** [comment]
I rebased this branch and gave it a test and it appears to work well.... merge?

**Comment by mtrudel** [comment]
I think I'm ok with merging it but I'd like to give @petermm the chance to chime in since this is their PR originally.

**Comment by petermm** [comment]
apologies for never getting back to this..

Think I did the simple work and @mtrudel the clever work;-)

I wont get a change to test it anytime soon, so if @hez has tested it I'm all for a merge..

**Comment by mtrudel** [comment]
Merged!

**Pull request merged**
